#!/bin/bash
echo "🎾 Tennis League Management System - Table Format Demo"
echo ""
echo "Now when you run your application and choose option 9 (View all players),"
echo "instead of seeing this ugly format:"
echo ""
echo "Player{playerId=19, name='Federico Chiesa', position='Forward', age=26, teamId=7, phoneNumber='555-7001'}"
echo "Player{playerId=20, name='Manuel Locatelli', position='Midfielder', age=25, teamId=7, phoneNumber='555-7002'}"
echo ""
echo "You will see this beautiful table format:"
echo ""
echo "┌─────────────────────────────────────────────────────────────────────────────────┐"
echo "│                                    PLAYERS                                      │"
echo "├─────┬──────────────────────┬─────────────┬─────┬───────┬─────────────────────┤"
echo "│ ID  │       NAME           │  POSITION   │ AGE │ TEAM  │    PHONE NUMBER     │"
echo "├─────┼──────────────────────┼─────────────┼─────┼───────┼─────────────────────┤"
echo "│ 19  │ Federico Chiesa      │ Forward     │ 26  │ 7     │ 555-7001            │"
echo "│ 20  │ Manuel Locatelli     │ Midfielder  │ 25  │ 7     │ 555-7002            │"
echo "│ 21  │ Matthijs de Ligt     │ Defender    │ 24  │ 7     │ 555-7003            │"
echo "└─────┴──────────────────────┴─────────────┴─────┴───────┴─────────────────────┘"
echo "Total Players: 3"
echo ""
echo "The same beautiful formatting applies to:"
echo "• Teams (option 1)"
echo "• Coaches (option 5)"
echo "• Players by team (option 13)"
echo ""
echo "To test this, run: java -cp \"target/classes:target/dependency/*\" TennisLeague.main.Main"
